stages:
  - test

variables: 
  DOCKER_TLS_CERTDIR: ''
  REMOTE_DIR: /mnt/project/java-frontend

test: 
  stage: test
  image: alpine:latest
  tags:
    - java-frontend
  before_script:
    - apk update && apk add git
    - git --version
    - git config --global --add safe.directory "$REMOTE_DIR"
  script:
    - echo "Trying to access the remote dir"
    - cd "$REMOTE_DIR" || exit 1
    - git remote -v
    - echo "Contents of $REMOTE_DIR :"
    - ls -la
    - echo "Local test succeed"
  only:
    - main

